# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11hrPn9Xx58H62reTmBn_3-xgF4X5bd1I
"""

print('Hello')